### ISSUE TITLE
Unable to import module 

### ISSUE THREAD

**Issue by kracekumar** [rfk/m2wsgi#8]
Here is my directory structure

```
In [11]: ls
app/           logs/             run/           wiktionary.json
circus.conf    m2wsgi_server.py  runserver.py*  wsgid.json
config.sqlite  mongrel2.conf     the.db
env/           README            tmp/
instance/      requirements.txt  wiktionary/


In [12]: __import__(modnm,fromlist=["*"])
Out[12]: <module 'wiktionary' from 'wiktionary/__init__.pyc'>

In [13]: modnm
Out[13]: 'wiktionary'

```

Apparently the command unable to find the module `wiktionary`

```
kracekumar@aadukalam:~/codes/python-wiktionary$ m2wsgi wiktionar
y.app tcp://127.0.0.1:9999
Traceback (most recent call last):
  File "/usr/local/bin/m2wsgi", line 9, in <module>
    m2wsgi.main()
  File "/usr/local/lib/python2.7/dist-packages/m2wsgi/__init__.py", line 224, in main
    app = load_dotted_name(args[0])
  File "/usr/local/lib/python2.7/dist-packages/m2wsgi/util/__init__.py", line 69, in load_dotted_name
    mod = __import__(modnm,fromlist=["*"])
ImportError: No module named wiktionary
```

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
